# Generated by Django 4.2.2 on 2023-06-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('tipo_dispositivo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('activo_viejo', models.CharField(max_length=25)),
                ('activo_nuevo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('error', 'Error'), ('mejora', 'Mejora'), ('nueva funcionalidad', 'Nueva Funcionalidad')], max_length=100)),
                ('requerimiento', models.CharField(max_length=200)),
                ('solucion', models.TextField(max_length=1000)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('dispositivos', models.ManyToManyField(to='dispositivos.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('servicios', models.ManyToManyField(to='dispositivos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('dispositivos', models.ManyToManyField(to='dispositivos.dispositivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.responsable')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.servicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.responsable'),
        ),
    ]
